import{a as P,S as E,i as a}from"./assets/vendor-CrlV4O_2.js";(function(){const n=document.createElement("link").relList;if(n&&n.supports&&n.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))r(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const s of o.addedNodes)s.tagName==="LINK"&&s.rel==="modulepreload"&&r(s)}).observe(document,{childList:!0,subtree:!0});function i(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function r(e){if(e.ep)return;e.ep=!0;const o=i(e);fetch(e.href,o)}})();const R="50702962-7cd53856c0773f25b2e4cfafa",x="https://pixabay.com/api/";async function p(t,n=1,i=15){const r={key:R,q:t,image_type:"photo",orientation:"horizontal",safesearch:!0,page:n,per_page:i};try{const e=await P.get(x,{params:r});return{images:e.data.hits,total:e.data.totalHits}}catch(e){throw console.error("Pixabay API error:",e),new Error("Failed to fetch images from Pixabay")}}const m=document.querySelector(".gallery"),y=new E(".gallery a",{captionsData:"alt",captionDelay:250});function L(t){return t.map(({webformatURL:n,largeImageURL:i,tags:r,likes:e,views:o,comments:s,downloads:q})=>`
        <div class="card">
          <a href="${i}">
            <img src="${n}" alt="${r}" loading="lazy" />
          </a>
          <div class="info">
            <p><strong>Likes</strong> ${e}</p>
            <p><strong>Views</strong> ${o}</p>
            <p><strong>Comments</strong> ${s}</p>
            <p><strong>Downloads</strong> ${q}</p>
          </div>
        </div>
      `).join("")}function A(t){m.innerHTML=L(t),y.refresh()}function I(t){m.insertAdjacentHTML("beforeend",L(t)),y.refresh()}function M(){m.innerHTML=""}function b(){document.querySelector(".loader-backdrop").classList.add("is-visible")}function c(){document.querySelector(".loader-backdrop").classList.remove("is-visible")}function v(){document.querySelector(".load-more").hidden=!1}function l(){document.querySelector(".load-more").hidden=!0}const f=document.querySelector("form");let g="",d=1;const h=15;let w=0,u=0;f.addEventListener("submit",async t=>{var i;t.preventDefault();const n=(i=f.elements["search-text"])==null?void 0:i.value.trim();if(!n){a.warning({title:"Warning",message:"Please enter a search query.",position:"topRight"});return}g=n,d=1,u=0,M(),l(),b();try{const{images:r,total:e}=await p(g,d,h);if(c(),w=Math.min(e,500),!r.length){a.error({title:"Error",message:"Sorry, there are no images matching your search query. Please, try again!",position:"topRight"});return}A(r),u=r.length,f.reset(),S(r.length)}catch(r){c(),a.error({title:"Error",message:"Failed to fetch images.",position:"topRight"}),console.error("Error fetching images:",r)}});document.querySelector(".load-more").addEventListener("click",async()=>{d+=1,b(),l();try{const{images:t}=await p(g,d,h);if(c(),!t.length){l(),a.info({title:"Info",message:"We're sorry, but you've reached the end of search results.",position:"topRight"});return}I(t),u+=t.length,O(),S(t.length)}catch(t){c(),v(),a.error({title:"Error",message:"Failed to load more images.",position:"topRight"}),console.error("Load more error:",t)}});function O(){const t=document.querySelector(".gallery .card");if(!t)return;const n=t.getBoundingClientRect().height;window.scrollBy({top:n*2,behavior:"smooth"})}function S(t){u>=w||t<h?(l(),a.info({title:"Info",message:"We're sorry, but you've reached the end of search results.",position:"topRight"})):v()}
//# sourceMappingURL=index.js.map
