import{a as S,S as q,i}from"./assets/vendor-CrlV4O_2.js";(function(){const n=document.createElement("link").relList;if(n&&n.supports&&n.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))r(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const l of o.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&r(l)}).observe(document,{childList:!0,subtree:!0});function a(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function r(e){if(e.ep)return;e.ep=!0;const o=a(e);fetch(e.href,o)}})();const P="50702962-7cd53856c0773f25b2e4cfafa",E="https://pixabay.com/api/";async function y(t,n=1,a=15){const r={key:P,q:t,image_type:"photo",orientation:"horizontal",safesearch:!0,page:n,per_page:a};try{const e=await S.get(E,{params:r});return{images:e.data.hits,total:e.data.totalHits}}catch(e){throw console.error("Pixabay API error:",e),new Error("Failed to fetch images from Pixabay")}}const L=document.querySelector(".gallery");document.querySelector(".loader");const B=new q(".gallery a",{captionsData:"alt",captionDelay:250});function R(t){return t.map(({webformatURL:n,largeImageURL:a,tags:r,likes:e,views:o,comments:l,downloads:v})=>`
        <div class="card">
          <a href="${a}">
            <img src="${n}" alt="${r}" loading="lazy" />
          </a>
          <div class="info">
            <p><strong>Likes</strong> ${e}</p>
            <p><strong>Views</strong> ${o}</p>
            <p><strong>Comments</strong> ${l}</p>
            <p><strong>Downloads</strong> ${v}</p>
          </div>
        </div>
      `).join("")}function x(){L.inserHTML=""}function f(t){L.insertAdjacentHTML("beforeend",R(t)),B.refresh()}const g=document.querySelector("form");document.querySelector(".gallery");const c=document.querySelector(".load-more"),h=document.querySelector(".loader");let m="",d=1;const b=15;let p=0,s=0;g.addEventListener("submit",async t=>{var a;t.preventDefault();const n=(a=g.elements["search-text"])==null?void 0:a.value.trim();if(!n){i.warning({title:"Warning",message:"Please enter a search query.",position:"topRight"});return}m=n,d=1,s=0,x(),c.hidden=!0,w();try{const{images:r,total:e}=await y(m,d,b);if(u(),p=e,f(r),s=r.length,!r.length){i.error({title:"Error",message:"Sorry, there are no images matching your search query. Please, try again!",position:"topRight"});return}f(r),s+=r.length,g.reset(),s>=p?(c.hidden=!0,i.info({title:"Info",message:"We're sorry, but you've reached the end of search results.",position:"topRight"})):c.hidden=!1}catch(r){u(),i.error({title:"Error",message:"Failed to fetch images.",position:"topRight"}),console.error("Error fetching images:",r)}});function w(){h.hidden=!1,c.after(h)}function u(){h.hidden=!0}c.addEventListener("click",async()=>{d+=1,w();try{const{images:t}=await y(m,d,b);u(),f(t),s+=t.length,A(),s>=p&&(c.hidden=!0,i.info({title:"Info",message:"We're sorry, but you've reached the end of search results.",position:"topRight"}))}catch(t){u(),i.error({title:"Error",message:"Failed to load more images.",position:"topRight"}),console.error("Load more error:",t)}});function A(){const t=document.querySelector(".gallery .card");if(!t)return;const n=t.getBoundingClientRect().height;window.scrollBy({top:n*2,behavior:"smooth"})}
//# sourceMappingURL=index.js.map
