import{a as P,S as E,i as a}from"./assets/vendor-CrlV4O_2.js";(function(){const n=document.createElement("link").relList;if(n&&n.supports&&n.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))t(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const s of o.addedNodes)s.tagName==="LINK"&&s.rel==="modulepreload"&&t(s)}).observe(document,{childList:!0,subtree:!0});function i(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function t(e){if(e.ep)return;e.ep=!0;const o=i(e);fetch(e.href,o)}})();const R="50702962-7cd53856c0773f25b2e4cfafa",x="https://pixabay.com/api/";async function y(r,n=1,i=15){const t={key:R,q:r,image_type:"photo",orientation:"horizontal",safesearch:!0,page:n,per_page:i};try{const e=await P.get(x,{params:t});return{images:e.data.hits,total:e.data.totalHits}}catch(e){throw console.error("Pixabay API error:",e),new Error("Failed to fetch images from Pixabay")}}const m=document.querySelector(".gallery");document.querySelector(".loader");const h=new E(".gallery a",{captionsData:"alt",captionDelay:250});function L(r){return r.map(({webformatURL:n,largeImageURL:i,tags:t,likes:e,views:o,comments:s,downloads:w})=>`
        <div class="card">
          <a href="${i}">
            <img src="${n}" alt="${t}" loading="lazy" />
          </a>
          <div class="info">
            <p><strong>Likes</strong> ${e}</p>
            <p><strong>Views</strong> ${o}</p>
            <p><strong>Comments</strong> ${s}</p>
            <p><strong>Downloads</strong> ${w}</p>
          </div>
        </div>
      `).join("")}function A(r){m.innerHTML=L(r),h.refresh()}function I(r){m.insertAdjacentHTML("beforeend",L(r)),h.refresh()}function M(){m.innerHTML=""}function b(){document.querySelector(".loader-backdrop").classList.add("is-visible")}function c(){document.querySelector(".loader-backdrop").classList.remove("is-visible")}function v(){document.querySelector(".load-more").hidden=!1}function l(){document.querySelector(".load-more").hidden=!0}const f=document.querySelector("form");let g="",d=1;const p=15;let S=0,u=0;f.addEventListener("submit",async r=>{var i;r.preventDefault();const n=(i=f.elements["search-text"])==null?void 0:i.value.trim();if(!n){a.warning({title:"Warning",message:"Please enter a search query.",position:"topRight"});return}g=n,d=1,u=0,M(),l(),b();try{const{images:t,total:e}=await y(g,d,p);if(c(),S=Math.min(e,500),!t.length){a.error({title:"Error",message:"Sorry, there are no images matching your search query. Please, try again!",position:"topRight"});return}A(t),u=t.length,f.reset(),q(t.length)}catch(t){c(),a.error({title:"Error",message:"Failed to fetch images.",position:"topRight"}),console.error("Error fetching images:",t)}});document.querySelector(".load-more").addEventListener("click",async()=>{d+=1,b(),l();try{const{images:r}=await y(g,d,p);if(c(),!r.length){l(),a.info({title:"Info",message:"We're sorry, but you've reached the end of search results.",position:"topRight"});return}I(r),h.refresh(),u+=r.length,O(),q(r.length)}catch(r){c(),v(),a.error({title:"Error",message:"Failed to load more images.",position:"topRight"}),console.error("Load more error:",r)}});function O(){const r=document.querySelector(".gallery .card");if(!r)return;const n=r.getBoundingClientRect().height;window.scrollBy({top:n*2,behavior:"smooth"})}function q(r){u>=S||r<p?(l(),a.info({title:"Info",message:"We're sorry, but you've reached the end of search results.",position:"topRight"})):v()}
//# sourceMappingURL=index.js.map
